### ISSUE TITLE
'zip' object has not attribute 'sort'

### ISSUE THREAD

**Issue by PkuRainBow** [ColumbiaDVMM/Spread-out_Local_Feature_Descriptor#2]
```
def ErrorRateAt95Recall(labels, scores):
    recall_point = 0.95
    # Sort label-score tuples by the score in descending order.
    sorted_scores = zip(labels, scores)
    sorted_scores.sort(key=operator.itemgetter(1), reverse=False)
```

I meet an error when excute to the lines "sorted_score.sort().."
The error information is 

> 'zip' object has not attribute 'sort'

Could you share me a solution ?

**Comment by PkuRainBow** [comment]
This is a problem caused by the change of the usage of ''zip" in Python3.  I tried to replace the line with 

> sorted(sorted_scores, key=operator.itemgetter(1), reverse=False)

**Comment by spongezhang** [comment]
Thanks for the information and fix. Haven't tested the code under python3
