### ISSUE TITLE
about the implementation based on hardnet

### ISSUE THREAD

**Issue by Danee-wawawa** [ColumbiaDVMM/Spread-out_Local_Feature_Descriptor#3]
Hi, thank you very much for sharing the code. 
I have checked the code based on hardnet that you provide, but I can't find the part of the implementation of ''Spread-out_Local_Feature_Descriptor'' in it. It seems that the code is just hardnet, could you tell me where is the part of spread-out descriptor in the hardnet code.
Thank you very much.

**Comment by spongezhang** [comment]
Sure. See HardNet.py line 404-405. If you enable gor, which is short for global orthogonal regularization, the regularization proposed in our paper, the trick will work. The actual implementation of gor is in Losses.py, line 156-162. Yes, the implementation of gor is that simple. :)

**Comment by Danee-wawawa** [comment]
Yes, I find it. Thank you very much.

**Comment by spongezhang** [comment]
No problem.
