### ISSUE TITLE
how many epoches did you use to evaluate a dataset ?

### ISSUE THREAD

**Issue by hurricane2018** [ColumbiaDVMM/Spread-out_Local_Feature_Descriptor#4]
![image](https://user-images.githubusercontent.com/36166137/38773469-37fbf870-401b-11e8-9c9c-3ba8db05a605.png)

The test accuracy is always change. Did you get the average precision of the test data ?

I mean, If we train 10 epoch, we can get a precision. If we train 20 epoches, we can get another result. How did you solve this problem ?

**Comment by spongezhang** [comment]
Hi Hurricane,

Due to randomness of the network training, the performance will change. It's true for all the DL based methods. We generally learn 10 epochs and take the average of 3 different trials. 

Best,
Xu

**Comment by hurricane2018** [comment]
Ok,
     got it. Thanks!
